### ISSUE TITLE
Unsatisifiable requirement

### ISSUE THREAD

**Issue by niwla23** [miquels/webdav-server-rs#2]
There are no docs how to install this and Cargo just fails:

webdav-handler = { path = "../webdav-handler-rs", version = "=0.2.0-alpha.4" }

**Comment by Niwla23** [comment]
Okay, I found it, but it should be documented
(https://github.com/miquels/webdav-handler-rs)

**Comment by miquels** [comment]
I know, I should release an actual 0.2.0 of webdav-handler-rs, and an actual 0.3.0 of webdav-server-rs. It will need at least one more alpha though, since I plan to change the configuration file format. TOML is too clunky, IMHO.

**Comment by miquels** [comment]
Fixed in latest version

**Comment by equwal** [comment]
> Okay, I found it, but it should be documented (https://github.com/miquels/webdav-handler-rs)

yep, still not in the doc
