### ISSUE TITLE
Troublesome Windows 10 Clients

### ISSUE THREAD

**Issue by florianjacob** [miquels/webdav-server-rs#7]
I have many troubles connecting with a Windows 10 Explorer client to a Linux server. From the Readme, this should work?
If you have tested this, maybe you could share a working configuration / way of setting up a Windows 10 client?

Both client and server seem to eventually crash. I tried “add network location”, “map network drive”, but the most stable way seems to be to use the command line like this:

`net use Z: https://example.org/Share /user:username *`

While displaying and reading from an anonymously-readble share seems to work, if I try to write to a share, Explorer crashes.
If I connect to a drive that requires authentication, I get a “Network path is not found”.

On the server part, individual tokio threads crash with this message:
```
webdav-server: thread 'tokio-runtime-worker' panicked at 'already mutably borrowed: BorrowError', /build/rustc-1.45.2-src/src/libcore/cell.rs:797:9
nginx: *1544 upstream prematurely closed connection while reading response header from upstream, server: example.org, request: "PROPFIND /Share HTTP/2.0", upstream: "http://[::1]:4918/Share", host: "example.org"
```

I know that this information is not enough for debugging, I'm mainly asking for one way that works for someone else that I can try to reproduce, and then see what's different from that what I am trying.

Thank you for this piece of software, KDE/Plasma with Dolphin and MacOS Finder works very well, and especially with Finder I never was able to get samba working!

**Comment by miquels** [comment]
Looks like that is a `RefCell` error. But there's only one place in the code where a `RefCell` is used, and that's in a thread_local section. Hmm.

It could be that you're using an old version. I just updated all code to the latest `tokio 1.0`. So can you:

- update to the latest stable Rust (`rustup update`) in case you hit a library bug (unlikely)
- pull the latest code from `master`

And try again?

If you still hit the same problem, please set the environment variable RUST_BACKTRACE before running the server, using `export RUST_BACKTRACE=full`, and see if you can get a better backtrace.
